CREATE TABLE JPA_DUMMY (id char(1))

CREATE PROCEDURE GET_COCKTAIL_COUNT(IN ZUTAT_NAME VARCHAR(255)) BEGIN select count(*) from JPA_COCKTAIL C where exists (select * from JPA_COCKTAILZUTAT Z, JPA_COCKTAIL_COCKTAILZUTAT CZ where Z.NAME=ZUTAT_NAME and CZ.ZUTAT_ID=Z.ID and CZ.COCKTAIL_ID=C.ID); END

CREATE PROCEDURE GET_ZUTAT_VOLPROZ(IN ZUTAT_NAME VARCHAR(255), OUT VOLPROZ DOUBLE) BEGIN select Z.VOLPROZ into VOLPROZ from JPA_COCKTAILZUTAT Z where Z.NAME=ZUTAT_NAME; END

CREATE PROCEDURE GET_COCKTAILS_WITH_ZUTAT(IN ZUTAT_NAME VARCHAR(255)) BEGIN select C.ID, C.NAME from JPA_COCKTAIL C, JPA_COCKTAILZUTAT Z, JPA_COCKTAIL_COCKTAILZUTAT CZ where Z.NAME=ZUTAT_NAME and CZ.ZUTAT_ID=Z.ID and CZ.COCKTAIL_ID=C.ID; END

CREATE PROCEDURE GET_ZUTAT_AND_COCKTAILS(IN ZUTAT_NAME VARCHAR(255)) BEGIN select Z.NAME from JPA_COCKTAILZUTAT Z where Z.NAME=ZUTAT_NAME; select C.NAME from JPA_COCKTAIL C, JPA_COCKTAILZUTAT Z, JPA_COCKTAIL_COCKTAILZUTAT CZ where Z.NAME=ZUTAT_NAME and CZ.ZUTAT_ID=Z.ID and CZ.COCKTAIL_ID=C.ID; END

